# 1. Votre lien JDBC de Neon
spring.datasource.url=jdbc:postgresql://ep-dry-truth-abnziz5o-pooler.eu-west-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_YGU6jSKAfwk8&sslmode=require&channelBinding=require

# 2. Vos identifiants Neon (parfois inclus dans l'URL, mais à répéter ici)
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YGU6jSKAfwk8

# 3. Configuration de création automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# 4. Le port de votre API
server.port=8080
# Désactiver Spring Security temporairement
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


